language: objective-c
osx_image: xcode61
rvm: 2.1.0
notifications:
  email: false
podfile: path/to/Podfile
before_install:
  - gem install xcpretty
  - cd project
script:
  - xcodebuild -project project.xcodeproj -scheme project test -sdk iphonesimulator8.1 -destination OS=8.1,name=iPhone | xcpretty -c; exit ${PIPESTATUS[0]}
